# aqui tenho que colocar o nome do pipeline
name: Primeiro Workflow
# em quais eventos de gatilho quero que dispare meu script
on:
  push:
    branches:
      - developer 
      - main
      - master
  pull_request:
      branches:
        - main
        - master
 # quais são os trabalhos (fluxos) a serem executados pelo workflow             
jobs:
  Primeiro-fluxo:
# este é o nome do fluxo de trabalho
    name: Job 1
    needs: Terceiro-fluxo
  # para ser executado nesta maquina virtual (container linux)
    runs-on: ubuntu-latest
  # agora irei incluir os passos do script
    steps:
      - name: Passo 1
        run: echo "Executando o primeiro passo do fluxo"
      - name: Passo 2
        run: echo "Executando o segundo passo do fluxo"
      - name: Passo 3
        run: echo "Executando o terceiro passo do fluxo"
  Segundo-fluxo:
# este é o nome do fluxo de trabalho
    name: Job 2
    needs: Primeiro-fluxo
  # para ser executado nesta maquina virtual (container linux)
    runs-on: ubuntu-latest
  # agora irei incluir os passos do script
    steps:
      - name: Passo 3
        run: echo "Executando o terceiro passo do fluxo"
      - name: Passo 4
        run: echo "Executando o quarto passo do fluxo"
      - name: Passo 5
        run: echo "Executando o quinto passo do fluxo"
  Terceiro-fluxo:
# este é o nome do fluxo de trabalho
    name: Job 3
  # para ser executado nesta maquina virtual (container linux)
    runs-on: ubuntu-latest
  # agora irei incluir os passos do script
    steps:
      - name: Passo 6
        run: echo "Executando o sexto passo do fluxo"
      - name: Passo 7
        run: echo "Executando o sétimo passo do fluxo"
      - name: Passo 8
        run: echo "Executando o oitavo passo do fluxo"
                
        
